name: kanban-backend
group: backend
replicaCount: 1
container:
  image: wkrzywiec/kanban-app:helm-course
  port: 8080
  env: 
    DB_SERVER: postgres
    POSTGRES_DB: kanban
    POSTGRES_USER: kanban
    POSTGRES_PASSWORD: kanban
service:
  type: ClusterIP
  port: 8080

database:
  enabled: true

postgresql:
  fullnameOverride: "postgres"
  image:
    tag: 11.14.0-debian-10-r17
  auth:
    username: "kanban"
    password: "kanban"
    database: "kanban"

test:
  enabled: true
  connection:
    endpoint: '/api/actuator'