apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: 10.14.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: database.enabled