apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullName" . }}
  labels: 
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:             
    app: {{ include "fullName" . }}
  ports:
    - port: {{ .Values.service.port }}       
      targetPort: {{ .Values.container.port }}